before_script:
  - ruby -v
  - which ruby
  - apt -qq update -y
  - apt -qq install -y default-jre
  - gem install bundler --no-document
  - bundle install --jobs=$(nproc) --path=deps --quiet
  - bundle clean

test:2.6:
  image: ruby:2.6
  script: bundle exec rake test
  except:
    - tags
  cache:
    key: ruby:2.6
    paths:
      - deps

test:2.7:
  image: ruby:2.7
  script: bundle exec rake test
  except:
    - tags
  cache:
    key: ruby:2.7
    paths:
      - deps

test:3.0:
  image: ruby:3.0
  script: bundle exec rake test
  except:
    - tags
  cache:
    key: ruby:3.0
    paths:
      - deps

test:3.1:
  image: ruby:3.1
  script: bundle exec rake test
  except:
    - tags
  cache:
    key: ruby:3.1
    paths:
      - deps

test:3.2:
  image: ruby:3.2
  script: bundle exec rake test
  except:
    - tags
  cache:
    key: ruby:3.2
    paths:
      - deps
