before_script:
  - ruby -v
  - which ruby
  - apt -qq update -y
  - apt -qq install -y default-jre
  - gem install bundler --no-document
  - bundle install --jobs=$(nproc) --path=deps --quiet

cache:
  paths:
    - deps/

test:2.2:
  image: ruby:2.2
  script:
    - bundle exec rake test

test:2.3:
  image: ruby:2.3
  script: bundle exec rake test

test:2.4:
  image: ruby:2.4
  script: bundle exec rake test

test:2.5:
  image: ruby:2.5-rc
  script: bundle exec rake test
